version: "3.2"

networks:
  proxy:
  socket_proxy:

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    privileged: yes
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket_proxy
    restart: always
    profiles: ["core"]

  traefik:
    image: traefik:v2.6.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    depends_on:
      - socket-proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--providers.docker.network=proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=$EMAIL"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    volumes:
      - $PWD/data/traefik/letsencrypt:/letsencrypt
    networks:
      - proxy
      - socket_proxy
    restart: always
    profiles: ["core"]

  jnsgruk:
    image: jnsgruk/jnsgr.uk:latest
    container_name: jnsgruk
    environment:
      WEBROOT: ./public
      REDIRECT_MAP_URL: https://gist.githubusercontent.com/jnsgruk/b590f114af1b041eeeab3e7f6e9851b7/raw
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jnsgruk.rule=Host(`jnsgr.uk`) || Host(`www.jnsgr.uk`)"
      - "traefik.http.routers.jnsgruk.entrypoints=websecure"
      - "traefik.http.routers.jnsgruk.tls=true"
      - "traefik.http.routers.jnsgruk.tls.certresolver=le"
    restart: unless-stopped
    profiles: ["jnsgruk"]

  barry:
    image: jnsgruk/bestbarry:latest
    container_name: barry
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.barry.rule=Host(`bestbarry.uk`) || Host(`www.bestbarry.uk`)"
      - "traefik.http.routers.barry.entrypoints=websecure"
      - "traefik.http.routers.barry.tls.certresolver=le"
      - "traefik.http.routers.barry.tls=true"
    restart: always
    profiles: ["barry"]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    profiles: ["core"]
